name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.3" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake git tar

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Lint
        run: bundle exec rubocop --parallel --display-cop-names
